services:
  app-build:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: app-build
    develop:
      watch:
        - action: rebuild
          path: ./app
          include:
            - "*.csproj"

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: app
    depends_on:
      app-build:
        condition: service_completed_successfully
        restart: true
      mssql:
        condition: service_healthy
    ports:
      - 5202:5202
      - 42042:42000
    environment:
      ConnectionStrings:DefaultConnection: "Server=tcp:mssql;Initial Catalog=appdb;User ID=sa;Password=P@ssw0rd;TrustServerCertificate=True"
    develop:
      watch:
        - action: rebuild
          path: ./app
          include:
            - "*.csproj"
            - Properties/

        - action: rebuild
          path: ./
          include:
            - Dockerfile
            - deploy/dev/app

        - action: sync+exec
          path: ./app/Data/Migrations
          target: /App/Data/Migrations
          exec:
            command: dotnet ef database update

        - action: sync+exec
          path: ./app/package.json
          target: /App/package.json
          exec:
            command: npm install

        - action: sync
          path: ./app
          target: /App
          ignore:
            - .git/
            - .vs/
            - .vscode/
            - node_modules/
            - dist/
            - bin/
            - obj/
            - "*.log"
            - "*.csproj"
            - Properties/
            - package.json
            - package-lock.json

  mssql:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: mssql
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: P@ssw0rd
      MSSQL_DATABASE: master
      MSSQL_PID: Express
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools18/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "P@ssw0rd",
          "-Q",
          "SELECT 1",
          "-No",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
